[NeMo W 2024-03-27 13:47:17 modelPT:165] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config :
    manifest_filepath: /manifests/combined_fisher_swbd_voxceleb12_librispeech/train.json
    sample_rate: 16000
    labels: null
    batch_size: 64
    shuffle: true
    is_tarred: false
    tarred_audio_filepaths: null
    tarred_shard_strategy: scatter
    augmentor:
      noise:
        manifest_path: /manifests/noise/rir_noise_manifest.json
        prob: 0.5
        min_snr_db: 0
        max_snr_db: 15
      speed:
        prob: 0.5
        sr: 16000
        resample_type: kaiser_fast
        min_speed_rate: 0.95
        max_speed_rate: 1.05
    num_workers: 15
    pin_memory: true
[NeMo W 2024-03-27 13:47:17 modelPT:172] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
    Validation config :
    manifest_filepath: /manifests/combined_fisher_swbd_voxceleb12_librispeech/dev.json
    sample_rate: 16000
    labels: null
    batch_size: 128
    shuffle: false
    num_workers: 15
    pin_memory: true
[NeMo I 2024-03-27 13:47:17 features:289] PADDING: 16
[NeMo I 2024-03-27 13:47:17 save_restore_connector:249] Model EncDecSpeakerLabelModel was successfully restored from /home/hyeons/.cache/huggingface/hub/models--nvidia--speakerverification_en_titanet_large/snapshots/0dc382f40121a5fbd34db10a2bb04d826c2be6a8/speakerverification_en_titanet_large.nemo.
  0%|                                                                                              | 0/21 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/home/hyeons/workspace/AudioFocus/run.py", line 65, in <module>
    run(vars(args))
  File "/home/hyeons/workspace/AudioFocus/run.py", line 53, in run
    trainer.train()
  File "/home/hyeons/workspace/AudioFocus/src/trainers/base.py", line 68, in train
    test_logs.update(self.test())
  File "/home/hyeons/workspace/AudioFocus/src/trainers/base.py", line 126, in test
    for mixed_voices, clean_voices, target_utter, target_voices in tqdm.tqdm(self.test_loader):
  File "/home/hyeons/miniconda3/envs/gp2/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/hyeons/miniconda3/envs/gp2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/hyeons/miniconda3/envs/gp2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/hyeons/miniconda3/envs/gp2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/hyeons/miniconda3/envs/gp2/lib/python3.10/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
soundfile.LibsndfileError: <exception str() failed>
Traceback (most recent call last):
  File "/home/hyeons/workspace/AudioFocus/run.py", line 65, in <module>
    run(vars(args))
  File "/home/hyeons/workspace/AudioFocus/run.py", line 53, in run
    trainer.train()
  File "/home/hyeons/workspace/AudioFocus/src/trainers/base.py", line 68, in train
    test_logs.update(self.test())
  File "/home/hyeons/workspace/AudioFocus/src/trainers/base.py", line 126, in test
    for mixed_voices, clean_voices, target_utter, target_voices in tqdm.tqdm(self.test_loader):
  File "/home/hyeons/miniconda3/envs/gp2/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/hyeons/miniconda3/envs/gp2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/hyeons/miniconda3/envs/gp2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/hyeons/miniconda3/envs/gp2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/hyeons/miniconda3/envs/gp2/lib/python3.10/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
soundfile.LibsndfileError: <exception str() failed>